apiVersion: apps/v1
kind: Deployment
metadata:
  name: blockchain-go
  labels:
    app: blockchain-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blockchain-go
  template:
    metadata:
      labels:
        app: blockchain-go
    spec:
      containers:
      - name: blockchain-go
        image: blockchain-go:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080

---

apiVersion: v1
kind: Service
metadata:
  name: blockchain-service
spec:
  type: NodePort
  selector:
    app: blockchain-go
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30100


